apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscale-demo
  template:
    metadata:
      labels:
        app: autoscale-demo
    spec:
      containers:
        - name: autoscale-demo
          image: autoscale-demo
          ports:
            - containerPort: 8000

